### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by Vickoh** [DerwenAI/pytextrank#10]
Fixed by changing the code on pytextrank (307) from:
            try:
                graph.edge[pair[0]][pair[1]]["weight"] += 1.0
            except KeyError:
                graph.add_edge(pair[0], pair[1], weight=1.0)
to:  
          if "edge" in dir(graph):
                graph.edge[pair[0]][pair[1]]["weight"] += 1.0
            else:
                graph.add_edge(pair[0], pair[1], weight=1.0)

**Comment by mohitagrwl12** [comment]
Fixed by replacing "graph.edge" with "graph.adj" on line 308 (based on networkx version 1.x to 2.0 migration guide https://networkx.github.io/documentation/latest/release/migration_guide_from_1.x_to_2.0.html)

**Comment by chandu8542** [comment]
Is the issue in question solved?

**Comment by twielfaert** [comment]
Replacing "graph.edge"with "graph.adj"works. Alternatively you can downgrade networkx to version 1.11

**Comment by clayms** [comment]
I solved a little differently https://github.com/ceteri/pytextrank/issues/18#issuecomment-390398883

**Comment by ceteri** [comment]
Resolve in the v1.2.0 release

**Comment by sleeplessai** [comment]
Now use nx.selfloops_edges(g) to solve.

**Comment by ceteri** [comment]
@sleeplessai which versions of `networkx` and `pytextrank` are you using?

This sounds like much earlier releases, which were subsequently resolved.
