### ISSUE TITLE
I get an error in the example "Stage 1"

### ISSUE THREAD

**Issue by colingoldberg** [DerwenAI/pytextrank#13]
Trying to run "stage 1" of the example (Python 3.6.4), I get error "__call__() got an unexpected keyword argument 'parse'".

Even the following gives me the error:
`
path_stage0 = 'dat/mih.json'
for graf in parse_doc(json_iter(path_stage0)):
    print(graf)
`
Error details:
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pytextrank-master/pytextrank/pytextrank.py", line 261, in parse_doc
    grafs, new_base_idx = parse_graf(meta["id"], graf_text, base_idx)
  File ".../pytextrank-master/pytextrank/pytextrank.py", line 193, in parse_graf
    doc = spacy_nlp(graf_text, parse=True)
TypeError: __call__() got an unexpected keyword argument 'parse'
`

**Comment by tomron** [comment]
I also get the same error

**Comment by jakubvalenta** [comment]
This is the same as issue #15. It seems to be fixed by PR #11.

**Comment by dmitrysenkovich** [comment]
is there any workaround? thanks!

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that should resolve these issues.
