### ISSUE TITLE
AttributeError: type object 'Language' has no attribute 'factory'

### ISSUE THREAD

**Issue by akhila66** [DerwenAI/pytextrank#135]
I'm getting this error.

**Comment by ceteri** [comment]
Hi @akhila66,

That error tends to happen when PyTextRank 3.x gets run with spaCy 2.x

A few quick questions to check:

- Which version of PyTextrank?
- Which version of spaCy?
- What operating system and version?
- Installation through `pip` or `conda`, or direct source installation from a cloned Git repo?
- Using any virtual environment, such as `venv`?
- Running within a notebook, such as JupyterLab ?

If you are running code inside of JupyterLab, there can also be problems with the path environment variables settings (which is a Conda problem)

**Comment by akhila66** [comment]
scipy              1.6.1
pytextrank         3.1.0
OS                        MAC
Using python3 - installed using pip3
No venv
running just python script.

**Comment by ceteri** [comment]
Also, which version of spaCy are you using?

**Comment by ceteri** [comment]
FWIW, here's where we were troubleshooting other instances of this error: 
<https://github.com/explosion/spaCy/discussions/7435>

In the case discussed where `pip3` and `venv` were getting used with spaCy 3.x installed, but `conda` had spaCy 2.x installed and it was overriding the Python executable path.

**Comment by akhila66** [comment]
I'm sorry.
Here it is 
spacy              3.0.5

**Comment by ceteri** [comment]
Thanks -

In this case, it's very likely the Python executable being used at the time of the `pip3` installs differs from the Python executable used when running the script.

A good way to test for this condition is to run from the command line:
```
python -m spacy info
```

Then add to your script:
```
import sys
print(sys.executable)
```

I have a hunch the two Python paths will not be the same.

FWIW, the `AttributeError: type object 'Language' has no attribute 'factory'` message is a spaCy 2.x error. So it's got to be getting invoked somewhere!  We'll get this :)
