### ISSUE TITLE
Add support for unicode characters

### ISSUE THREAD

**Issue by abs51295** [DerwenAI/pytextrank#14]
Currently while decoding a file, `'ascii' codec can't decode byte` error shows up. It would be good to have unicode character support. Thanks :)

**Comment by abs51295** [comment]
Should I send a PR for this?

**Comment by ceteri** [comment]
Since v2.0.x is now a spaCy extension, are there any more issues with utf-8?

**Comment by abs51295** [comment]
I don't think it should be a problem. Closing it and will re-open it if I encounter this again. Thanks @ceteri :)
