### ISSUE TITLE
Error: Can't find factory for 'textrank' for language English....

### ISSUE THREAD

**Issue by r76941156** [DerwenAI/pytextrank#148]
Hi there,

Does any know how to fix below errors when running example code?

Thanks.
==========================

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    nlp.add_pipe("textrank")
  File "/usr/local/lib64/python3.6/site-packages/spacy/language.py", line 773, in add_pipe
    validate=validate,
  File "/usr/local/lib64/python3.6/site-packages/spacy/language.py", line 639, in create_pipe
    raise ValueError(err)
ValueError: [E002] Can't find factory for 'textrank' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, parser, beam_parser, entity_linker, ner, beam_ner, entity_ruler, lemmatizer, tagger, morphologizer, senter, sentencizer, textcat, textcat_multilabel, en.lemmatizer

**Comment by Ankush-Chander** [comment]
Hi @r76941156 

It seems like you are trying to add  `textrank` in the nlp pipeline without importing it.

Adding this statement should resolve the issue before the `nlp.add_pipe("textrank")` should resolve the issue.

`import pytextrank`

**Comment by r76941156** [comment]
Hi there,

Below is the code example I copied from the main page. 

I think the issue is the integration of new Spacy v3 and pytextank. Thanks.
==========
import spacy
import pytextrank

# example text
text = "Compatibility of systems of linear constraints over the set of natural numbers. Criteria of compatibility of a system of linear Diophantine equations, strict inequations, and nonstrict inequations are considered. Upper bounds for components of a minimal set of solutions and algorithms of construction of minimal generating sets of solutions for all types of systems are given. These criteria and the corresponding algorithms for constructing a minimal supporting set of solutions can be used in solving all the considered types systems and systems of mixed types."

# load a spaCy model, depending on language, scale, etc.

nlp = spacy.load("en_core_web_sm")

# add PyTextRank to the spaCy pipeline
nlp.add_pipe("textrank")
doc = nlp(text)

# examine the top-ranked phrases in the document
for phrase in doc._.phrases:
    print(phrase.text)
    print(phrase.rank, phrase.count)
    print(phrase.chunks)

**Comment by Ankush-Chander** [comment]
Please share following information.
1. Output of following command?
`python -m spacy info`
2. And which version of pytextrank you are using currently?

**Comment by r76941156** [comment]
For now:

pytextrank: 2.1.0 (No change)

and

spacy: 2.3.0 (from 3.0.5)





________________________________

**Comment by Ankush-Chander** [comment]
Please install latest pytextrank
`pip install pytextrank==3.1.1`

It should work with spacy 3.0.5

For more details please refer [faq](https://github.com/DerwenAI/pytextrank/blob/main/docs/faq.md#attributeerror-type-object-language-has-no-attribute-factory).

**Comment by ceteri** [comment]
Thank you @r76941156 for the report. I'll add to @Ankush-Chander's excellent suggestions above:

Another thing to check is about which Py environment is getting called. It looks like you're running within a notebook?

There's a known issue between Conda and JupyterLab, where the Conda installer rewrites the Bash profile's path environment variables – in what I would call a very "kludgy" way ;)  The end result is that while you may have a Python virtual environment working well when you run scripts and get command line info (e.g., with spaCy 3.x) then the Python executable changes when running JupyterLab (but not the older Jupyter).

Therefore, also check within the running notebook about which `sys.executable` is actually running, since it can be different than the one on the command line that launched JupyterLab. <https://derwen.ai/docs/ptr/faq/>
