### ISSUE TITLE
Error on spacy 2.0

### ISSUE THREAD

**Issue by trimbilrepo** [DerwenAI/pytextrank#15]
I'm using
`pip install -U pytextrank`
to install and tried to execute the stage1.py but then error appear on the execution process
```
doc = spacy_nlp(graf_text, parse=True)
TypeError: __call__() got an unexpected keyword argument 'parse'
```
I tried to remove arg parse=True but then another error raise.

is there any compatibly issue on pytextrank on scapy version 2.0?

thank you

**Comment by soumendrak** [comment]
@trimbilrepo and team, Did you get any workaround for it? I am also facing the same issue.

**Comment by colingoldberg** [comment]
Some time ago, when I also got this error, I made two changes in file pytextrank.py, that I think made a difference. It looked like the code had not been updated for a recent version of spacy. I think it then ran, but unfortunately, I don't remember the details. My apologies if this doesn't help much.

The changes were:
around line 192:
 doc = spacy_nlp(graf_text)

around line 434:
doc = spacy_nlp(text.strip())

Colin Goldberg

**Comment by jakubvalenta** [comment]
See PR #11 for a fix.

**Comment by clayms** [comment]
For those that don't want to wait for PR #11, the exact lines @colingoldberg referred to that you need to change are:

https://github.com/ceteri/pytextrank/blob/181ea41375d29922eb96768cf6550e57a77a0c95/pytextrank/pytextrank.py#L193

`doc = spacy_nlp(graf_text)` 

and 

https://github.com/ceteri/pytextrank/blob/181ea41375d29922eb96768cf6550e57a77a0c95/pytextrank/pytextrank.py#L421

`doc = spacy_nlp(text.strip())`

Then you will likely also have to fix this https://github.com/ceteri/pytextrank/issues/18#issuecomment-390398883
