### ISSUE TITLE
Post-Processing on keyword Extraction with pytextrank

### ISSUE THREAD

**Issue by Jansonboss** [DerwenAI/pytextrank#156]
Question:

Hi! The TextRank paper says there's a post-processing step which combined adjacent keywords together. Can someone helps me point to the related part within the source code? (I can't find this step...)

Original sentence in paper: `_as potential keywords by the TextRank algorithm are marked in the text, and sequences of adjacent keywords are collapsed into a multi-word keyword.`

**Comment by ceteri** [comment]
Hi @Jansonboss, great question.

I have a hunch you may be interested in this recent discussion: <https://github.com/DerwenAI/pytextrank/issues/152>

TL;DR:

1. After 12 years, and many production deployments (Java => Scala => Python), we've found it necessary to improve _recall_ for multi-word phrases so there were improvements over time
2. The current section of code mentioned in #152 is going away soon, to be replaced with a graph-based _entity linking_ feature set based on integrating together into `kglab` + pytextrank`

Does that help?

**Comment by Jansonboss** [comment]
Thank you so much!
