### ISSUE TITLE
Add TextRank visualisations

### ISSUE THREAD

**Issue by louisguitton** [DerwenAI/pytextrank#158]
After talking with @pacoid, I'd like to contribute a visualisation of TextRank to this package.
We already have `BaseTextRank.write_dot` which uses `graphviz`.
The proposed method would be named `BaseTextRank.plot_keyphrases`.

## How it looks

![image](https://user-images.githubusercontent.com/7823843/116809412-33c80280-ab3e-11eb-935e-b8b443e0972b.png)

```python
import pathlib

import spacy
import pytextrank
import altair as alt
import pandas as pd

nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("textrank", last=True)
text = pathlib.Path("dat/cfc.txt").read_text()
doc = nlp(text)

def plot_keyphrases(doc: spacy.tokens.Doc) -> alt.Chart:
    """Plot profile of a doc's keyphrases' ranks."""
    source = pd.DataFrame([p.__dict__ for p in doc._.phrases]).drop("chunks", axis=1).reset_index()
    c = (
        alt.Chart(source)
        .mark_bar()
        .encode(x="index", y="rank", color="count", tooltip=["text", "rank", "count"])
        .properties(title="Keyphrase profile of the article")
    )
    return c

plot_keyphrases(doc)
```

## Problem

The issue is that this very simple code requires to bring 2 (big) dependencies: `altair` and `pandas`.

I see 3 options, let me know your thoughts @ceteri @Ankush-Chander on what option you prefer:

### Option 1: bring in the dependencies for everyone as part of base dependencies

`pandas` and `altair` are common dependencies IMO.

### Option 2: use extra dependenciese

In `setup.py`, I could add

```diff
        extras_require = {
            "base": base_packages,
            "docs": docs_packages,
+            "viz": ["altair"]
            },
```

And then users who want to use that feature can do `pip install pytextrank[viz]`

### Option 3: downgrade viz to matplotlib and bring that as a dependency

We could also write that method using matplotlib. The graph won't be as nice with the interactive tooltips etc... but the dependency wouldn't be as big.

```python
import matplotlib as mpl
from matplotlib import pyplot as plt

x = range(len(doc._.phrases))
height = [p.rank for p in doc._.phrases]
norm = mpl.colors.Normalize(vmin=0, vmax=max(p.count for p in doc._.phrases))
cmap = mpl.cm.ScalarMappable(norm=norm, cmap=mpl.cm.Blues)
cmap.set_array([])
plt.bar(x, height, width=0.8, color=[cmap.to_rgba(p.count) for p in doc._.phrases])
```

![image](https://user-images.githubusercontent.com/7823843/116809374-01b6a080-ab3e-11eb-8b6c-c0f5bd397315.png)

**Comment by Ankush-Chander** [comment]
@louisguitton Great idea!

I see visualisation as a developer tool and would be helpful in analysing results and iterating fast. From that perspective Option 2 sounds good.

@ceteri

**Comment by ceteri** [comment]
Wow, outstanding!  Thank you @louisguitton  :)

I like **Option 2** although how would we handle the `altair` dependency in the `BaseTextRank.plot_keyphrases` code without its import?  If there's a good way, great!!  Otherwise, **Option 1** would be good!

FWIW, I'm _really_ tempted to remove the `graphviz` dependency and simply write the DOT files with our own code.  Also, once we have `kglab` integration, there will be a much larger set of graph file serialization formats available. The `graphviz` code relies on some external code that's sometimes iffy.

**Comment by louisguitton** [comment]
Thanks for the added context on `graphviz`. Before removing it, I could also move `graphviz`  to the `viz` dependencies.

Great question on checking for whether a dependency is installed @pacoid I missed that point.
So the shortcut would be to bring the dependency only in the function and not at the top of the module. But that would go against pep8 :trollface: , so usually I still bring the dependency at the top with a check, watch this space.
