### ISSUE TITLE
Could .txt or other input files used in this project?

### ISSUE THREAD

**Issue by xiaoxielnino** [DerwenAI/pytextrank#16]
Note that the input files in the examples are all .json format. I was wondering that whether the .txt or other type input files can be used in the project?

**Comment by bazzmx** [comment]
Open the text file, create a dict with this file and give it and id if you want and dump it to a json, this way if you have a bunch of text files json_iter will handle them. Would it be easier to use a .txt file or glob imo.

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release, which now runs as a spaCy extension. Any input format acceptable for spaCy should work fine.
