### ISSUE TITLE
Add CI using GithubActions

### ISSUE THREAD

**Issue by louisguitton** [DerwenAI/pytextrank#160]
## Why

While contributing my last PR, I noticed we were not exercising the `pre-commit` hooks and the `pytest` tests on each branch.

This is important to add in order to lower the bar for external contributions and lower the maintenance burden.

## What

Add a Github Actions Continuous Integration (CI) workflow that will:
- pip install the package (make sure install works)
- run pre-commit hooks
- run tests

**Comment by ceteri** [comment]
Many thanks!
