### ISSUE TITLE
Serious bug in get_tiles? 

### ISSUE THREAD

**Issue by teucer** [DerwenAI/pytextrank#17]
I believe there is a serious bug in the line [284](https://github.com/ceteri/pytextrank/blob/master/pytextrank/pytextrank.py#L284) in pytextrank.py. 

Indeed once the unneeded words are filtered out (`keeps = list(filter(lambda w: w.word_id > 0, graf))`) the word indices have holes. 

The corrected line should be 

```
if (j - i) < size:
      yield (w0.root, w1.root)
```

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that should resolve this issue.
