### ISSUE TITLE
[suggestion] use Span in scrubber?

### ISSUE THREAD

**Issue by Ankush-Chander** [DerwenAI/pytextrank#180]
@ceteri 

I think if we can give user more flexibility  if we pass span to scrubber instead of span.text.

Before
```
       data: typing.List[typing.Tuple[str, float, Span]] = [
            (self.scrubber(span.text), rank, span) for span, rank in all_phrases.items()
        ]
```
 
After
```
        data: typing.List[typing.Tuple[str, float, Span]] = [
            (self.scrubber(span), rank, span) for span, rank in all_phrases.items()
        ]        
``` 

So that user can use pos_tags, matchers etc(basically everything available to a token) for phrase cleanup which is quite tedious if user gets to operate on text.

Let me know of your thoughts.

Thanks in advance.

**Comment by Ankush-Chander** [comment]
Here"s two example scrubbers for the use case of cleaning articles from phrases:

Before
```
@spacy.registry.misc("article_scrubber")
def stop_words_scrubber():
	def scrubber_func(text: str) -> str:
		articles = ["a", "the", "their"]
		return " ".join([w for w in text.split() if w not in articles])
	return scrubber_func


```

After:
```
@spacy.registry.misc("article_scrubber")
def stop_words_scrubber():
	def scrubber_func(text_span: Span) -> str:
		for token in text_span:
			if token.pos_ !="DET":
				break
			text_span = text_span[1:]
		return text_span.text
	return scrubber_func

```

**Comment by ceteri** [comment]
Hi @Ankush-Chander, that's great!

Given the operation on spans instead, would it make sense to consolidate two of the functions passed as arguments into one `scrubber` that potentially could handle both?

I'm trying to find cases where that might limit a pipeline. Seems okay?

Also, I'm glad to learn about `@spacy.registry.misc()` :)

**Comment by Ankush-Chander** [comment]
Hey @ceteri 
 
 By passing span to the scrubber user has freedom to operate in both text space(string manipulation as it"s happening in current setup) as well as doc space(token manipulation). 
 `span.text` vs `span`

One concern is backward compatibility. If user has already defined scrubbers that take text as input,

I can think of two alternatives here:
1. Handle exception to support cases where scrubber expects text instead of span.

```
        try:
            data: typing.List[typing.Tuple[str, float, Span]] = [
                (self.scrubber(span), rank, span) for span, rank in all_phrases.items()
            ]
        except AttributeError as err:
            data: typing.List[typing.Tuple[str, float, Span]] = [
                (self.scrubber(span.text), rank, span) for span, rank in all_phrases.items()
            ]
```   
This should covers all 3 cases
a. no user defined scrubber
b. text based scrubber
c. span based scrubber

2.  FWIW another option I suggest is that we introduce breaking change and encourage users to create span based scrubbers.
Users will need to add a line and change signature in their scrubbers.

P.S:  Spacy recent versions  mandated configs to be JSON serializable so users will need to make changes in their scrubber anyways. That is: Register them using `@spacy.registry.misc()` instead of directly passing function in config.(as discussed [here](https://github.com/DerwenAI/pytextrank/issues/172#issuecomment-869135052))

**Comment by ceteri** [comment]
Excellent!  I think a breaking change is best – we need to catch-up with spaCy in terms of how configs are handled, and there's also that multiprocessing pipe issue.

I have a block of time tomorrow for testing and to make a new release.
