### ISSUE TITLE
[New Need]Input some paragraphs then return less paragraphs but complete  sentences back

### ISSUE THREAD

**Issue by CaptXiong** [DerwenAI/pytextrank#185]
I used to using the sentence summarize function named "summary", now I am trying to summarize the whole section by return less paragraphs but complete with same number sentences as input.
I have written a subclass of TextRank to accomplish the logic that sort paragraphs with their average sentence score.
So I think that if there is a need to add this function in TextRank.

**Comment by ceteri** [comment]
Thank you @CaptXiong, do you want to add that as a pull request? 
Sounds like having a "dial" to adjust the document length. Would be great to check out!

**Comment by CaptXiong** [comment]
Sure! I will pull a request then.
