### ISSUE TITLE
Not working in spanish

### ISSUE THREAD

**Issue by davesnake01** [DerwenAI/pytextrank#192]
Hi, it seems it does not work in spanish, this is the error

Can't find factory for 'textrank' for language Spanish (es). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

I've install 

this is my code

import pytextrank
import spacy
nlp = spacy.load("es_core_news_sm")

def resumen(body):

    #Tokens
    doc = nlp(body)
    tokens = doc.ents
    print(tokens)

    # add PyTextRank to the spaCy pipeline
    nlp.add_pipe("textrank")

    # examine the top-ranked phrases in the document
    for phrase in doc._.phrases:
        print(phrase.text)
        print(phrase.rank, phrase.count)
        print(phrase.chunks)

    return phrase.chunks, tokens

**Comment by DayalStrub** [comment]
you should be adding textrank before you apply `nlp` (the spacy pipeline) to the text, `body`. if you read the documentation you will see some examples of how to use it.

**Comment by ceteri** [comment]
@davesnake01 does that resolve the problem?
