### ISSUE TITLE
spacy call error: __call__() got an unexpected keyword argument 'parse'

### ISSUE THREAD

**Issue by asberk** [DerwenAI/pytextrank#20]
```
~/.local/lib/python3.6/site-packages/pytextrank/pytextrank.py in parse_graf(doc_id, graf_text, base_idx, spacy_nlp)
    191     markup = []
    192     new_base_idx = base_idx
--> 193     doc = spacy_nlp(graf_text, parse=True)
    194 
    195     for span in doc.sents:

TypeError: __call__() got an unexpected keyword argument 'parse'
```
spacy.\_\_version\_\_ == 2.0.11

seems that `spacy_nlp(graf)` does not have the option `parse` (it now only has the option `disable`).

**Comment by clayms** [comment]
I think this is the same issue that was addressed here:
https://github.com/ceteri/pytextrank/issues/15#issuecomment-392323261

**Comment by Dobatymo** [comment]
Same here. Still not fixed.

**Comment by asberk** [comment]
It's been awhile since I dealt with this, but I believe @clayms link above did the trick (at least until the Pull Request is accepted).
