### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by romanovzky** [DerwenAI/pytextrank#21]
Hi there, I've been looking at your code and example for a long time and I still have no idea how to use this.

I have documents in string format, what JSON format should they have if I want to use the stages as in the examples?

I find there's a crucial piece of information missing in the documentation, which is how to use the functionality of this package with a simple document in string format (or list of strings, representing sentences). As I don't know beforehand what JSON format I have to convert my text to in order to use the stage pipeline.

Cheers

**Comment by AshwiniPatil5** [comment]
Stuck at the same point. So did you find a way further for this?

**Comment by mrshu** [comment]
Given the path used in the [example](https://github.com/ceteri/pytextrank/wiki), it seems that the following file is the actual input: https://github.com/ceteri/pytextrank/blob/master/dat/mih.json

Thus, the JSON format should be:

```
{
  "id": "777",
  "text": "Compatibility of systems of linear constraints over the set of natural numbers. Criteria of compatibility of a system of linear Diophantine equations, strict inequations, and nonstrict inequations are considered. Upper bounds for components of a minimal set of solutions and algorithms of construction of minimal generating sets of solutions for all types of systems are given. These criteria and the corresponding algorithms for constructing a minimal supporting set of solutions can be used in solving all the considered types systems and systems of mixed types."
}
```

Hope this helps!

**Comment by satendrapandeymp** [comment]
You can clone this: https://github.com/satendrapandeymp/pytextrank
and run ttJson.py by specifying either file or directory having .txt data which will be converted to JSON for further use.

**Comment by sayak1711** [comment]
Like @mrshu said each line in your input will contain a json {"id": anyinteger, "text": "documentcontent"}.
Name your file mih.json and put it in a folder named dat. The create a python file and paste the code in [this](https://github.com/ceteri/pytextrank/blob/master/example.ipynb) in it. dat folder and your python file should be in same parent folder. Then run it.

**Comment by RupeshGoud** [comment]
[
`{`
"id": anyinteger,
 "text": "documentcontent"
},
{
"id": anyinteger,
 "text": "documentcontent"
},....
]
Then this format is not working why ??

**Comment by sayak1711** [comment]
@RupeshGoud Your input file will be a json file.
Here's how your json file will look like when you open it in notepad/text editor.
**Line1** {"id": anyinteger, "text": "documentcontent"}
**Line2** {"id": anyinteger, "text": "documentcontent"}

What you have pasted above is a list of dictionaries/json

**Comment by RupeshGoud** [comment]
Yes, does this library supports handling list of dictionaries??@sayak1711

**Comment by prionkor** [comment]
Thank you for your comments. Cleared up a lot of things. But looking at the example it has two variables to start with 

```
path_stage0 = "dat/mih.json"
path_stage1 = "o1.json"

```

what is `o1.json` file?

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release, which now runs as a spaCy extension, so its usage is much simpler.
