### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by AshwiniPatil5** [DerwenAI/pytextrank#22]
Hi Team,
It would be of great help if you could guide in this regard.
1) Is there a way to use the functionality of this package with a simple text document.
2) If not, I have documents and paragraphs in text(.txt) format. So what would be the input JSON format for the functions as given in the examples(Stages).

**Comment by satendrapandeymp** [comment]
You can clone this: https://github.com/satendrapandeymp/pytextrank
and run ttJson.py by specifying either file or directory having .txt data which will be converted to JSON for further use.

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release, which now runs as a spaCy extension. This code and its usage are both substantially simplified and run much faster.
