### ISSUE TITLE
Slow while execution

### ISSUE THREAD

**Issue by arunzz** [DerwenAI/pytextrank#25]
It is pretty slow when executed for a medium sized content.
Are there any tips to improve the performance? Kindly let know.
It takes around 30 seconds for a 512 KB content in both python 2 and 3.
Using latest spacy as well.

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that run much faster and require less memory.
