### ISSUE TITLE
Expected input JSON format is not documented / clear

### ISSUE THREAD

**Issue by j-siddle** [DerwenAI/pytextrank#27]
I'm currently working my way through the examples, and I found the documentation around the input formats to be quite unclear. Specifically, the schema isn't documented (in my understanding), and is only hinted at in the docs.

From looking at the example input, and reviewing the code, I've deduced that the input should consist of one JSON document per line, however I don't know how to structure my content to best suit this format. For example should I break a larger document into paragraphs, then include one per line in the JSON input? Or should the complete text to be summarised be included in a single 'text' element within the JSON.

Thanks,
J

**Comment by atiq222** [comment]
Input format is unclear. I am passing some sentences as one json. Got KeyError: 'text'

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that remove the need for those JSON input files. Now the text input happens entirely through the spaCy pipeline.
