### ISSUE TITLE
why does the project use  the length of RankedLexeme to sort the key phrases

### ISSUE THREAD

**Issue by liuvic** [DerwenAI/pytextrank#30]
why does the project use  the length of RankedLexeme to sort the key phrases?
the length are the same with each other.

def normalize_key_phrases (json_iter, ranks, stopwords=None, spacy_nlp=None, skip_ner=True):
       ......
       for rl in sorted(phrase_lex.values(), key=lambda rl: len(rl), reverse=True):

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that have much simpler and faster code.
