### ISSUE TITLE
why does the algorithm filter out  the verbs?

### ISSUE THREAD

**Issue by liuvic** [DerwenAI/pytextrank#31]
I do not know why does the algorithm filter out  the verbs?

def limit_keyphrases (json_iter, phrase_limit=10):
    .....
    for rl in lex:
        if rl.pos[0] != "v":
            if (used > phrase_limit) or (rl.rank < rank_thresh):
                return

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release, where that can be parameterized by updating the `TextRank.pos_kept` list.
