### ISSUE TITLE
Can't find model 'en'.

### ISSUE THREAD

**Issue by wcollins-ebsco** [DerwenAI/pytextrank#32]
Windows 10
Python 3.6
running Jupyter notebook in virtualenv
installed pytextrank with pip successfully
ran -m spacy download en
...
    Linking successful
    c:\ml\env\lib\site-packages\en_core_web_sm -->
    c:\ml\env\lib\site-packages\spacy\data\en
    You can now load the model via spacy.load('en')

Trying to follow example:

with open(path_stage1, 'w') as f:
    for graf in pytextrank.parse_doc(pytextrank.json_iter(path_stage0)):
        ...

I get:
OSError                                   Traceback (most recent call last)
<ipython-input-60-ce47b119e0f5> in <module>()
      3 
      4 with open(path_stage1, 'w') as f:
----> 5     for graf in pytextrank.parse_doc(pytextrank.json_iter(path_stage0)):
      6         f.write("%s\n" % pytextrank.pretty_print(graf._asdict()))
      7         # to view output in this notebook

c:\ml\env\lib\site-packages\pytextrank\pytextrank.py in parse_doc(json_iter)
    259                 print("graf_text:", graf_text)
    260 
--> 261             grafs, new_base_idx = parse_graf(meta["id"], graf_text, base_idx)
    262             base_idx = new_base_idx
    263 

c:\ml\env\lib\site-packages\pytextrank\pytextrank.py in parse_graf(doc_id, graf_text, base_idx, spacy_nlp)
    185     if not spacy_nlp:
    186         if not SPACY_NLP:
--> 187             SPACY_NLP = spacy.load("en")
    188 
    189         spacy_nlp = SPACY_NLP

c:\ml\env\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     19     if depr_path not in (True, False, None):
     20         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 21     return util.load_model(name, **overrides)
     22 
     23 

c:\ml\env\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    117     elif hasattr(name, 'exists'):  # Path or Path-like to model data
    118         return load_model_from_path(name, **overrides)
--> 119     raise IOError(Errors.E050.format(name=name))
    120 
    121 

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by ceteri** [comment]
Thanks - that default downloaded model name has changed to `en_core_web_sm` - although this parameter will go away in the upcoming pytextrank 2.x release.
