### ISSUE TITLE
Error in example.ipynb

### ISSUE THREAD

**Issue by LAW68** [DerwenAI/pytextrank#36]
I tried running the example associated with PYTEXT rank:-
https://github.com/DerwenAI/pytextrank/blob/master/example.ipynb

And I got the following error:-

  File "C:\Users\lee.williams\AppData\Local\Continuum\anaconda3\lib\site-packages\pytextrank\pytextrank.py", line 315, in build_graph
    for pair in get_tiles(map(WordNode._make, meta["graf"])):

TypeError: string indices must be integers

Any help would be appreciated. As the example output looks fine on the URL above

Regards

Lee

**Comment by ceteri** [comment]
We've exchanged email about this issue, but for anyone else reading here:
check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that should resolve these issues.
