### ISSUE TITLE
Error while running example.py 

### ISSUE THREAD

**Issue by vikaskumarjha9** [DerwenAI/pytextrank#41]
While running example, the following error occurred, any help will be appreciated.
>>> doc = nlp(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vikas/PycharmProjects/NLP-NMT/venv/lib/python3.5/site-packages/spacy/language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/home/vikas/github_projects/pytextrank/pytextrank/pytextrank.py", line 532, in PipelineComponent
    Doc.set_extension("phrases", force=True, default=self.calc_textrank())
  File "/home/vikas/github_projects/pytextrank/pytextrank/pytextrank.py", line 391, in calc_textrank
    self.collect_phrases(chunk)
  File "/home/vikas/github_projects/pytextrank/pytextrank/pytextrank.py", line 347, in collect_phrases
    rank = self.ranks[node_id]
KeyError: 29

**Comment by ceteri** [comment]
Thank you @vikaskumarjha9 will try to find and fix the issue there.

Could you please provide some more details?

- What is the text used? (so the bug can be reproduced)
- What OS are you using?
- `pip freeze` output to show which version of Python, spaCy, etc.?

**Comment by rockman25** [comment]
I had the same problem. Turns out I had conflicting versions of networkx. Pytextrank was trying to use networkx 1.1 instead of 2.4. Once I uninstalled the old version it worked fine.

**Comment by vikaskumarjha9** [comment]
@ceteri 
What is the text used? (so the bug can be reproduced)
>The default that example program refers to, I did not use any other file explicitly.
What OS are you using?
>I am using Ubuntu 16.04
Output of pip freeze
>Package            Version   
------------------ ----------
blis               0.4.1     
boto               2.49.0    
boto3              1.9.76    
botocore           1.12.76   
bz2file            0.98      
certifi            2018.11.29
chardet            3.0.4     
Click              7.0       
cycler             0.10.0    
cymem              2.0.3     
dateparser         0.7.0     
decorator          4.4.1     
dill               0.2.8.2   
docutils           0.14      
editdistance       0.4       
en-core-web-sm     2.2.0     
gensim             3.6.0     
graphviz           0.13.2    
idna               2.8       
importlib-metadata 0.23      
jmespath           0.9.3     
kiwisolver         1.0.1     
langdetect         1.0.7     
matplotlib         3.0.2     
more-itertools     7.2.0     
murmurhash         1.0.2     
networkx           2.4       
nltk               3.4       
numpy              1.15.4    
pip                19.3.1    
plac               1.1.3     
preshed            3.0.2     
procname           0.3       
protobuf           3.7.1     
pyparsing          2.3.1     
pytextrank         2.0.0     
python-dateutil    2.7.5     
pytz               2018.7    
regex              2018.11.22
requests           2.21.0    
s3transfer         0.1.13    
scikit-learn       0.20.2    
scipy              1.2.0     
setuptools         39.1.0    
singledispatch     3.4.0.3   
six                1.12.0    
sklearn            0.0       
smart-open         1.7.1     
spacy              2.2.2     
srsly              0.2.0     
stanfordnlp        0.1.2     
stompest           2.3.0     
summa              1.2.0     
textrank           0.1.0     
thinc              7.3.1     
torch              1.0.0     
torchtext          0.3.1     
tqdm               4.29.0    
tzlocal            1.5.1     
urllib3            1.24.1    
wasabi             0.4.0     
zipp               0.6.0

**Comment by vikaskumarjha9** [comment]
Thank you.
