### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by shadylpstan** [DerwenAI/pytextrank#46]
When extracting keywords,
` pytextrank.normalize_key_phrases(path_stage1, ranks) `
function gives the following error.
**RecursionError: maximum recursion depth exceeded in comparison**

**Comment by ceteri** [comment]
Thank you @shadylpstan, although that appears to be from a much earlier version of PyTextRank which isn't supported for current (2.x) releases of spaCy.

 - which version of spaCy are you using?
 - which version of PyTextRank?
 - which platform are in use: OS, IDE, virtual environments?
 - example snippet of calling code?
 - what input?

Many thanks -
