### ISSUE TITLE
Example file throws KeyError: 1255

### ISSUE THREAD

**Issue by oldskewlcool** [DerwenAI/pytextrank#47]
Have not been able to get either the long form (from wiki) or short form (from github readme) files to work successfully.

The file @ https://github.com/DerwenAI/pytextrank/blob/master/example.py throws a KeyError: 1255 when run. Output for this is below.

I have been able to get the example from the github page working but only for very small strings. Anything larger than a few words throws a KeyError with varying number depending on the length of the string.

Can't figure out the issue even using all input (txt files) from the example on the wiki page and changing the spacy version to various releases from 2.0.0 to present.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-c1b0ed2fd5c8> in <module>()
     31     text = f.read()
     32 
---> 33 doc = nlp(text)
     34 
     35 print("pipeline", nlp.pipe_names)

/home/pete/.local/lib/python3.5/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    433             if not hasattr(proc, "__call__"):
    434                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 435             doc = proc(doc, **component_cfg.get(name, {}))
    436             if doc is None:
    437                 raise ValueError(Errors.E005.format(name=name))

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in PipelineComponent(self, doc)
    530         """
    531         self.doc = doc
--> 532         Doc.set_extension("phrases", force=True, default=self.calc_textrank())
    533         Doc.set_extension("textrank", force=True, default=self)
    534 

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in calc_textrank(self)
    389 
    390         for chunk in self.doc.noun_chunks:
--> 391             self.collect_phrases(chunk)
    392 
    393         for ent in self.doc.ents:

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in collect_phrases(self, chunk)
    345             if key in self.seen_lemma:
    346                 node_id = list(self.seen_lemma.keys()).index(key)
--> 347                 rank = self.ranks[node_id]
    348                 phrase.sq_sum_rank += rank
    349                 compound_key.add(key)

KeyError: 1255

**Comment by ceteri** [comment]
Thank you @oldskewlcool, let's work through this. 

The exception trace above is very helpful.  FWIW, we haven't seen this issue previously.

Can you provide a few other details please, to help troubleshoot this?

 - code snippet of how PyTextRank is being called within a spaCy pipeline
 - which version of PyTextRank?
 - what platform: OS, any IDE, virtual environment?
 - looks like you're using Py 3.5, correct?
 - also, let's tie the error trace that we're troubleshooting to a specific context: a version of spaCy, a particular text input

**Comment by oldskewlcool** [comment]
Appreciate the fast reply @ceteri and happy to provide more details.


**System Details**
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
Python 3.5.3
networkx==2.4
pytextrank==2.0.0
spacy==2.2.3
graphviz==0.13.2
IDE = Jupyter Notebook V4.2.3
venv = none

**Code Snippets**
This ticket was filed against code snippet @ https://github.com/DerwenAI/pytextrank/blob/master/example.py

This snippet is being run using the files in /dat as input.

However a simpler example also produces this issue. The snippet below is from the Usage section of readme.md

Full snippet:

import spacy
import pytextrank

# example text
text = "Compatibility of systems of linear constraints over the set of natural numbers. Criteria of compatibility of a system of linear Diophantine equations, strict inequations, and nonstrict inequations are considered. Upper bounds for components of a minimal set of solutions and algorithms of construction of minimal generating sets of solutions for all types of systems are given. These criteria and the corresponding algorithms for constructing a minimal supporting set of solutions can be used in solving all the considered types systems and systems of mixed types."

# load a spaCy model, depending on language, scale, etc.
nlp = spacy.load("en_core_web_sm")

# add PyTextRank to the spaCy pipeline
tr = pytextrank.TextRank()
nlp.add_pipe(tr.PipelineComponent, name="textrank", last=True)

doc = nlp(text)

# examine the top-ranked phrases in the document
for p in doc._.phrases:
    print("{:.4f} {:5d}  {}".format(p.rank, p.count, p.text))
    print(p.chunks)

Stack Trace:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-3dfc4d097ec9> in <module>()
     12 nlp.add_pipe(tr.PipelineComponent, name="textrank", last=True)
     13 
---> 14 doc = nlp(text)
     15 
     16 # examine the top-ranked phrases in the document

/home/pete/.local/lib/python3.5/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    433             if not hasattr(proc, "__call__"):
    434                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 435             doc = proc(doc, **component_cfg.get(name, {}))
    436             if doc is None:
    437                 raise ValueError(Errors.E005.format(name=name))

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in PipelineComponent(self, doc)
    530         """
    531         self.doc = doc
--> 532         Doc.set_extension("phrases", force=True, default=self.calc_textrank())
    533         Doc.set_extension("textrank", force=True, default=self)
    534 

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in calc_textrank(self)
    389 
    390         for chunk in self.doc.noun_chunks:
--> 391             self.collect_phrases(chunk)
    392 
    393         for ent in self.doc.ents:

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in collect_phrases(self, chunk)
    345             if key in self.seen_lemma:
    346                 node_id = list(self.seen_lemma.keys()).index(key)
--> 347                 rank = self.ranks[node_id]
    348                 phrase.sq_sum_rank += rank
    349                 compound_key.add(key)

KeyError: 8


**Additional Notes**
In the above code snippet if the text variable is changed to:

text = "linear constraints over the"

The example runs successfully and the resulting output is:

0.4330     1  linear constraints
[linear constraints]
0.3333     1  linear
[linear]

However if the text variable is changed to:

text = "linear constraints over the set of natural numbers"

The resulting output is again an error, in this case:

KeyError                                  Traceback (most recent call last)
<ipython-input-2-a928471c5640> in <module>()
     12 nlp.add_pipe(tr.PipelineComponent, name="textrank", last=True)
     13 
---> 14 doc = nlp(text)
     15 
     16 # examine the top-ranked phrases in the document

/home/pete/.local/lib/python3.5/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    433             if not hasattr(proc, "__call__"):
    434                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 435             doc = proc(doc, **component_cfg.get(name, {}))
    436             if doc is None:
    437                 raise ValueError(Errors.E005.format(name=name))

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in PipelineComponent(self, doc)
    530         """
    531         self.doc = doc
--> 532         Doc.set_extension("phrases", force=True, default=self.calc_textrank())
    533         Doc.set_extension("textrank", force=True, default=self)
    534 

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in calc_textrank(self)
    389 
    390         for chunk in self.doc.noun_chunks:
--> 391             self.collect_phrases(chunk)
    392 
    393         for ent in self.doc.ents:

/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py in collect_phrases(self, chunk)
    345             if key in self.seen_lemma:
    346                 node_id = list(self.seen_lemma.keys()).index(key)
--> 347                 rank = self.ranks[node_id]
    348                 phrase.sq_sum_rank += rank
    349                 compound_key.add(key)

KeyError: 4

**Comment by oldskewlcool** [comment]
Some updates after playing around with this further:

- A fresh venv, with only 'pip install pytextrank' ran, produces the same KeyError.

- The code from explain_algo.ipynb, from the wiki, also produces the same issue (in either fresh venv or ran globally). In the explain_algo.ipynb example it appears the KeyError may stem from the link_sentence function. When this is executed it returns a lemma_graph dict with 24 entries vs the 31 labels (all 31 of which appear in the lemma_seen and labels variables in the ipynb example).

- Curiously, running the explain_algo.ipynb on Google colab executes successfully. This is using both the demo text and also various other text strings and making no other changes.

**Comment by epetros** [comment]
Having the same issue.
It runs well in Google Colab but having KeyError: ...  in Google Cloud VM.

**Comment by ceteri** [comment]
That's quite odd @epetros, since almost all of the dev + test for this code is done in the VM instances of Compute Engine on Google Cloud Platform.

Could you please describe more about what configurations you have on that VM for the libraries described in `requirements.txt` ?

**Comment by epetros** [comment]
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux

absl-py==0.9.0
astor==0.8.1
blis==0.4.1
boto==2.49.0
boto3==1.10.45
botocore==1.13.45
cachetools==4.0.0
catalogue==1.0.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cymem==2.0.3
decorator==4.4.1
distro==1.0.1
docutils==0.15.2
filelock==3.0.12
fire==0.2.1
Flask==1.1.1
gast==0.2.2
gdown==3.8.3
gensim==3.8.1
google-auth==1.10.0
google-auth-oauthlib==0.4.1
google-compute-engine==20191210.0
google-pasta==0.1.8
graphviz==0.13.2
grpcio==1.26.0
h5py==2.10.0
idna==2.8
importlib-metadata==1.5.0
itsdangerous==1.1.0
Jinja2==2.10.3
jmespath==0.9.4
joblib==0.14.1
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
murmurhash==1.0.2
networkx==2.4
nltk==3.4.5
numpy==1.18.0
oauthlib==3.1.0
opt-einsum==3.1.0
pandas==0.25.3
plac==1.1.3
preshed==3.0.2
protobuf==3.11.2
pt-core-news-sm==2.2.5
pyasn1==0.4.8
pyasn1-modules==0.2.7
pytextrank==2.0.0
python-apt==1.4.1
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.2
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
s3transfer==0.2.1
scikit-learn==0.22
scipy==1.4.1
six==1.13.0
smart-open==1.9.0
spacy==2.2.3
srsly==1.0.1
tensorboard==2.0.2
tensorflow==2.0.0
tensorflow-estimator==2.0.1
termcolor==1.1.0
thinc==7.3.1
tqdm==4.41.0
unattended-upgrades==0.1
urllib3==1.25.7
wasabi==0.6.0
Werkzeug==0.16.0
wrapt==1.11.2
zipp==1.1.0

**Comment by epetros** [comment]
doc = nlp(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/spacy/language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py", line 532, in PipelineComponent
    Doc.set_extension("phrases", force=True, default=self.calc_textrank())
  File "/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py", line 394, in calc_textrank
    self.collect_phrases(ent)
  File "/usr/local/lib/python3.5/dist-packages/pytextrank/pytextrank.py", line 347, in collect_phrases
    rank = self.ranks[node_id]
KeyError: 52

**Comment by epetros** [comment]
Same code runs well in Google Colab.

**Comment by jake-aft** [comment]
I was recieved the errors on GCP AI Notebooks, I assumed it was my error or an issue with the beta notebooks. I did have it running locally without errors previously.  sorry I did not keep the instance or the error messages. Sorry I can't be of more help at the moment. I maybe able to recreate the issue later, i'll let you know if I do.

**Comment by jake-aft** [comment]
I did find my error messages actually.


> jupyter@intel-20200128-205057:~$ python3 -V
> Python 3.5.3


**From the server**

> jupyter@intel-20200128-205057:~$ python3 -d example.py
> Traceback (most recent call last):
>   File "example.py", line 34, in <module>
>     doc = nlp(text)
>   File "/home/jupyter/.local/lib/python3.5/site-packages/spacy/language.py", line 402, in __call__
>     doc = proc(doc, **component_cfg.get(name, {}))
>   File "/home/jupyter/.local/lib/python3.5/site-packages/pytextrank/pytextrank.py", line 532, in PipelineComponent
>     Doc.set_extension("phrases", force=True, default=self.calc_textrank())
>   File "/home/jupyter/.local/lib/python3.5/site-packages/pytextrank/pytextrank.py", line 391, in calc_textrank
>     self.collect_phrases(chunk)
>   File "/home/jupyter/.local/lib/python3.5/site-packages/pytextrank/pytextrank.py", line 347, in collect_phrases
>     rank = self.ranks[node_id]
> KeyError: 1402

From the Notebook

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-64-5813f4c15a91> in <module>
> ----> 1 doc = nlp(text)
>       2 # print(doc)
> 
> ~/.local/lib/python3.5/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
>     400             if not hasattr(proc, "__call__"):
>     401                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
> --> 402             doc = proc(doc, **component_cfg.get(name, {}))
>     403             if doc is None:
>     404                 raise ValueError(Errors.E005.format(name=name))
> 
> ~/.local/lib/python3.5/site-packages/pytextrank/pytextrank.py in PipelineComponent(self, doc)
>     530         """
>     531         self.doc = doc
> --> 532         Doc.set_extension("phrases", force=True, default=self.calc_textrank())
>     533         Doc.set_extension("textrank", force=True, default=self)
>     534
> 
> ~/.local/lib/python3.5/site-packages/pytextrank/pytextrank.py in calc_textrank(self)
>     389
>     390         for chunk in self.doc.noun_chunks:
> --> 391             self.collect_phrases(chunk)
>     392
>     393         for ent in self.doc.ents:
> 
> ~/.local/lib/python3.5/site-packages/pytextrank/pytextrank.py in collect_phrases(self, chunk)
>     345             if key in self.seen_lemma:
>     346                 node_id = list(self.seen_lemma.keys()).index(key)
> --> 347                 rank = self.ranks[node_id]
>     348                 phrase.sq_sum_rank += rank
>     349                 compound_key.add(key)
> 
> KeyError: 496

**Comment by ceteri** [comment]
Many thanks @epetros and @jake-aft!

I guess I was too busy working in GCP and Colab to notice that GCP added AI Notebooks ;)

This should help us identify the cause.  Nothing sticks out in the package versions. The odd thing still is the intermittent behavior on VMs and Colab.

**Comment by epetros** [comment]
Any ideas about how to try and sort this issue?

**Comment by ajkl** [comment]
I faced this on python 3.5 and upgrading to python 3.6 fixed it. Not sure about the root cause.

**Comment by epetros** [comment]
Using python 3.6 makes the problem go away, indeed. Thanks

**Comment by ceteri** [comment]
Many thanks, this should help us to be able to debug the root cause.

**Comment by junchen1992** [comment]
dict.keys() is not ordered prior to Python 3.6. So the line `node_id = list(self.seen_lemma.keys()).index(key)` would not work for older Python versions.

See: [PEP 468](https://www.python.org/dev/peps/pep-0468/#specification)
> dict in CPython 3.6 is now ordered, similar to PyPy.

**Comment by junchen1992** [comment]
@ceteri Maybe the README should be updated to indicate the version of Python should be 3.6 or later. Or I could submit a PR to make it compatible with Python3.x.
