### ISSUE TITLE
Singular vs plural across documents

### ISSUE THREAD

**Issue by merrillaldrich** [DerwenAI/pytextrank#49]
Question: I am new at this and working from the example script to extract key phrases from about 800 separate documents. The tool is great! I notice in the results that some documents will produce a singular word in a key phrase (like "donor") while other documents in the set produce the plural of the same word ("donors"). In the ideal case I would like to collapse those into just one version, either singular or plural. Can you suggest an approach to do that? Is there any feature that would convert the found keywords to their singular, for example?

**Comment by ceteri** [comment]
Thank you kindly @merrillaldrich 

Internally, `PyTextRank` is using `spaCy` to determine a *lemma* for each noun or verb. For nouns that's converting plural to singular:
```
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("donors")

for t in doc:
    print(t.lemma_)
```

That should work for simple cases, but it may have troubles with compound phrases, when there are homonyms with very different meanings, etc.

There is a "lemma graph" data structure maintained inside of `PyTextRank` which possibly could be used across documents -- it has the data used to generate the network diagram. That would require means of populating data structures from a previous run.  

Looking from a more general perspective and a more analytic approach than the one above: you're talking about aggregating and disambiguating phrases extracted from different documents.

Short answer: There are a few ways to do that, depending on your time available.

Long answer: Some people use ML models (e.g., the Sesame Street gang of "transformers") to handle this. Others approach disambiguation problems by using graphs, e.g., *knowledge graph* projects which can help guide the process of aggregating and disambiguating. Think of it as a customized thesaurus.  FWIW, I use both in my ["day job"](https://github.com/Coleridge-Initiative/RCGraph) although the latter approach tends to be more of our focus.

**Comment by merrillaldrich** [comment]
That helps a lot, thanks! I'm getting good enough results by taking the key phrases that come out of textrank and then using code like your example to lemmatize and store those. So if I feed in a document that produces 'the donors' it converts to 'the donor.' For my case it just has to be close, not perfect :-)

**Comment by ceteri** [comment]
Great!  Meanwhile, we'll keep working here on having a "pluggable" means for knowledge graphs to help my `PyTextRank` a bit smarter!
