### ISSUE TITLE
summarization as a pipeline task

### ISSUE THREAD

**Issue by shyamcody** [DerwenAI/pytextrank#65]
Hi, so thanks for writing this awesome package. But is there any direct way to use summarization as there are pipelines for other tasks? Only thing I have found about summarization is the explain_summ.ipynb. please mention it if there is one.

**Comment by ceteri** [comment]
Great question @shyamcody -

There's an example of using *extractive summarization* within a spaCy pipeline in the [`example.py`](https://github.com/DerwenAI/pytextrank/blob/master/example.py) script:

```
with open("dat/lee.txt", "r") as f:
    text = f.read()
    doc = nlp(text)

    for sent in doc._.textrank.summary(limit_phrases=15, limit_sentences=5):
        print(sent)
```

Does that provide what you were looking for?

**Comment by shyamcody** [comment]
Yeah, I was looking for that only. For some reason, it missed my notice. Thanks for the answer! Can you also point out the place where I can see all the parameters of the summary method? (i.e. if it is syntactic or POS filters working and whether I can modify or turn them on/off, tolerance limit, iteration numbers, and others) That will be a big help.
