### ISSUE TITLE
Adding multilingual support with spaCy models

### ISSUE THREAD

**Issue by dvsrepo** [DerwenAI/pytextrank#7]
# Idea

Using spaCy as core NLP library for pytextrank opens up the possibility of supporting new 
languages other than English.

# Initial analysis

Currently, as of spaCy 1.8.x there are four official languages supported: en, de, fr and more recently es. 

I have performed an initial analysis and testing with two new languages: (1) German and (2) Spanish.
Of course, as with the English models, the user would need to run `python -m spacy download de` or `python -m spacy download es`.

According to my local tests executing the example notebook for German and Spanish, the following would be needed in pytextrank to support a new language:

1. Make lang configurable and have [https://github.com/ceteri/pytextrank/blob/master/pytextrank/pytextrank.py#L187](url) loading the language identified by its ISO code.

2. [CAVEAT] If the language is available in spaCy but does not include any of the required features: (1) POS, (2) NER, and (3) noun chunking method, anything else?. pytextrank should show a warning/error message. E.g., here:  [https://github.com/ceteri/pytextrank/blob/master/pytextrank/pytextrank.py#L423](url) for noun_chunking or here [https://github.com/ceteri/pytextrank/blob/master/pytextrank/pytextrank.py#L480](url) for NER

# Current status

Out the other 3 official languages, one of them would be supported out of the box (German) and other would be supported in the next release (Spanish only lacks noun_chunking in 1.8.2, which is currently implemented on the master branch and will be in principle be included in the next release, see [https://github.com/explosion/spaCy/pull/1096/commits/5b385e7d78fd955d97b59024645d2592bdbc0949](url))
French would need to implement NER and noun_chunking.

I would be happy to contribute code and examples if needed :-)

Dani

**Comment by Shawn-Zhenshan-Jin** [comment]
@dvsrepo Hi Daniel, thanks for your contribution and I think taking spaCy as the core NLP library really enhanced the potential of `pytextrank`. I'm wondering that is it possible to plug the `self-trained English spaCy model`, which can recognize other entities instead of the default entities in default English spaCy model, to the backend of `pytextrank`? If so, what would be a general process of it? Thank you!

**Comment by bazzmx** [comment]
well... I changed one detail on the tutorial and It's working with catalan (self made spacy model)

f.write('{}\n'.format(pytextrank.pretty_print(graf._asdict()),spacy_nlp='ca_core_news_sm'))

And it is working fine, the better your model, the better the results

**Comment by danielp3011** [comment]
Is there a tutorial for how to use it with German already somewhere?

**Comment by ceteri** [comment]
The `2.0.0` version is in testing now and should be ready for a release candidate by early next week, or before. It's refactored to be a spaCy extension, so it works with whichever language model you're using in spaCy. Will post a note here when that's ready -- the development branch is `spacy_pipeline`

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release, which now supports multiple languages with spaCy, as @dvsrepo described above.

**Comment by danielp3011** [comment]
@ceteri Thank you!
