### ISSUE TITLE
remove stopwords

### ISSUE THREAD

**Issue by Fan-Luo** [DerwenAI/pytextrank#72]
hi,

It seems the function `load_stopwords` in `pytextrank.py` is never called. 
Would you consider passing an argument when initializing to enable and disable removing the stopwords? And another argument to choose among pos and tag?

Besides, is it possible to make the `pharse` similar to a `span`, to allow access `token.pos_` for each token in a `pharse`?

**Comment by ceteri** [comment]
Thank you @Fan-Luo, there's an example of using `load_stopwords` in the [`sample.py`](https://github.com/DerwenAI/pytextrank/blob/master/sample.py) code.  It's a really good question whether to have this as an parameter in the constructor.  Given the new "component factory" architecture that allows for stateful pipeline components, it may be more powerful to leave this as a method in the class, but also have as a configuration parameter.

Also, the `Phrase` objects now are built as lists of `Span` -- see the `Phrase.chunks` member.  Does that provide what you were asking about?

FWIW, in the upcoming `kglab` integration, there will be much more explicit representation of the `token.pos_` metadata, etc.

**Comment by Fan-Luo** [comment]
Thank you @ceteri 
I ended up revised the code manually in my local, making small changes, such as replacing `token.lemma_` with `token.lemma_.lower().strip()`, etc.
I will try out the the latest version.

**Comment by ceteri** [comment]
BTW, the support for stop words was refactored into the configuration, i.e., as a configuration parameter when the pipeline component for TextRank gets created: https://derwen.ai/docs/ptr/sample/#stop-words
