### ISSUE TITLE
min_phrases are not minimum spans for each phrase

### ISSUE THREAD

**Issue by Fan-Luo** [DerwenAI/pytextrank#73]
Hi,

The [explain_algo.ipynb](https://colab.research.google.com/github/DerwenAI/pytextrank/blob/master/explain_algo.ipynb#scrollTo=IpqRPb3vWPVT) mentioned:
> Since noun chunks can be expressed in different ways (e.g., they may have articles or prepositions), we need to find a minimum span for each phrase based on combinations of lemmas...

But he code below does not do what it states. 
```
import operator

min_phrases = {}

for compound_key, rank_tuples in phrases.items():
    l = list(rank_tuples)
    l.sort(key=operator.itemgetter(1), reverse=True)
    
    phrase, rank = l[0]
    count = counts[compound_key]
    
    min_phrases[phrase] = (rank, count)
```

The min_phrases did not seem change the phrase at all, let alone `find a minimum span for each phrase`.

**Comment by ceteri** [comment]
Good points there @Fan-Luo, in the upcoming `kglab` integration, the `min_phrases` post-processing for TextRank algorithms will be updated substantially.
