### ISSUE TITLE
Differences between 2.1.0 and 3.0.0

### ISSUE THREAD

**Issue by debraj135** [DerwenAI/pytextrank#90]
Are the changes between the two versions of pytextrank documented anywhere? 

The queries seem to be giving different results, so I would like to understand if that is because of changes to spaCy or to the algorithm itself?

Thank you for your help.

**Comment by ceteri** [comment]
Thank you @debraj135, this report is much appreciated!

There were changes in spaCy 3.0.x that required changes in pipeline configuration and set up. Also some code updates in the algorithm implementation. Its core logic should be the same, except loops replaced with comprehensions.

While our unit tests showed consistent results, I'm eager to hear about any differences? Are there examples to show the differences in results between these releases?  

FWIW, in general, changes between `pytextrank` releases get logged in [`changelog.txt`](https://github.com/DerwenAI/pytextrank/blob/master/changelog.txt)

**Comment by ceteri** [comment]
@debraj135 another point that may be important to note:

TextRank as an algorithm is sensitive to the underlying parsers used – in this case statistical parsers. These tend to be multi-stage pipelines with trained models at each stage, which can lead to complex interactions. FWIW, there's more discussion at [*2020 NLP Industry  Survey*](https://gradientflow.com/2020nlpsurvey/)

PyTextRank is sensitive to the results coming from spaCy, in particular the pipeline components for segmentation (tokenizer, sentence splitter), PoS tagger, and noun chunks.  We've seen substantial changes in ranked phrase extraction as those components change, especially in our arc as an open source project from OpenNLP (2009), TextBlob (2016), spaCy 1.x (2017), spaCy 2.x (2019), and now spaCy 3.x which has a big rewrite of components now largely based on deep learning models.  I would expect some changes based on that, although I'd prefer to be more structured in how to measure and report about these changes.

Two outcomes:

- we should incorporate some appropriate benchmark tests to compare ranking across a suite of input docs
- will add better documentation about this area of dependencies in our new FAQ

**Comment by debraj135** [comment]
@ceteri Thank you for your prompt response. I appreciate this. 

I will get back to you soon on this with an example showing the difference in output, along with the corresponding package versions.

**Comment by Lord-V15** [comment]
@debraj135 are you done with this issue?
Maybe @ceteri can then close it.

**Comment by debraj135** [comment]
Unfortunately, I haven't been able to find the time to revisit this. Please feel free to close it and investigate if you find it necessary.

**Comment by ceteri** [comment]
Thank you @debraj135

**Comment by debraj135** [comment]
@ceteri, I don't believe this needs a separate issue. 

I wanted to understand if there is any documentation explaining the logic between [here](https://github.com/DerwenAI/pytextrank/blob/6dd286136e72b9081fbdec76d1e51a06e17a4bd7/pytextrank/base.py#L546) and [here](https://github.com/DerwenAI/pytextrank/blob/6dd286136e72b9081fbdec76d1e51a06e17a4bd7/pytextrank/base.py#L553). 

It is not clear to me why the phrase rank is the square root of the `sum rank / (span length + # non-lemmas)`. More specifically, why add span length and non lemmas, aren't you over counting the non lemmas here. Also, why the square root?

Along similar lines, the motivation behind the formula for the non lemma discount, as well as its purpose in line 553 is unclear to me. It would be great if you could help me build some intuition around this.

Why is it not sufficient to simply use `sum rank / span length`?

Thank you for any response, and kudos for the great work!
