### ISSUE TITLE
After installing pytextrank unable to import it

### ISSUE THREAD

**Issue by mahekshah5858** [DerwenAI/pytextrank#99]
Hi, 
After installing pytextrank, when I am trying to import it, it gives following error.
I tried import spacy before pytextrank but its still not working.

 import pytextrank
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mahek Shah\.conda\envs\up\lib\site-packages\pytextrank\__init__.py", line 24, in <module>
    @Language.factory("textrank", default_config=_DEFAULT_CONFIG)
AttributeError: type object 'Language' has no attribute 'factory'

**Comment by ceteri** [comment]
Thank you @mahekshah5858 

I can recreate this on Ubuntu 18.04 LTS, and am working on a quick fix.

BTW, a few questions would really help us:

- which version of PyTextRank are you using?
- which version of spaCy?
- which version of Python?
- which operating system?

Also, did you install via `pip` or `conda` or by cloning the repo and running the set up?

Many thanks -

**Comment by ceteri** [comment]
Digging into this further, I can recreate this on:
- Ubuntu 18.04 LTS
- running Python 3.6

However, PyTextRank requires Python 3.7+ so the Python version would be my first question for troubleshooting.  Also, there may be issues with other tooling not installed properly.

If you are on Ubuntu, in general you want to have the Python tooling set up:
```
apt install python3-pip python3-setuptools python3.7 python3.7-venv
```

The `spaCy` docs have a good installer wizard: <https://spacy.io/usage#installation>

If you're using `pip` be sure to run
```
pip install -U pip setuptools wheel
```
prior to installing `spaCy` or you may run into problems with it.


At that point, on a newly launched Ubuntu instance in the cloud, with the installations for Ubuntu, Python, spaCy listed above, then the rest of the installation and sample code at <https://derwen.ai/docs/ptr/start/> works fine.

**Comment by ceteri** [comment]
Revisiting this issue -- now it's reproducible on macOS when running inside a JupyterLab notebook.
See <https://github.com/explosion/spaCy/discussions/7435>

Note: this case doesn't appear to be reproducible on Ubuntu.

**Comment by ceteri** [comment]
@mahekshah5858, as it turns out, I hit this problem on my MacBook Pro also -- although only when running spaCy and pytextrank inside of JupyterLab.  Inside of Jupyter there was no problem.

Here's the issue documented: <https://github.com/explosion/spaCy/discussions/7435>

JupyterLab is both a library and an executable.  Conda is relatively aggressive about munging the path environment variable in one's bash profile when its installer runs.  TL;DR:  the Conda path my override your `venv` environment when running JupyterLab.

Just curious, were you also running within JupyterLab?

**Comment by mahekshah5858** [comment]
No I was using it via command line. And after creating the new virtual env and fresh installation of spacy and pytextrank worked for me. It seems that the version of spacy and pytextrank was not compatible with each other.
@ceteri  Thanks for helping me out.
